services:
  auth_service:
    build: .
    container_name: auth_service
    env_file:
      - .env
    depends_on:
      - auth_db
    ports:
      - "5000:5000"
    restart: unless-stopped

  auth_db:
    image: postgres:16
    container_name: auth_postgres
    env_file:
      - .env
    volumes:
      - auth_pg_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  auth_pg_data:
